### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 8030: Connection refused

### ISSUE THREAD

**Issue by srlagisetty** [mudler/ekcp#4]
Getting error curl: (7) Failed to connect to 127.0.0.1 port 8030: Connection refused locally on Mac 
any help please?

**Comment by mudler** [comment]
Hi, thanks for reporting the issue!

I've never tried on Mac, but the default docker-compose file sets network mode to `host`. Are you sure something else is not blocking it ? (firewall, network configuration) 

Also, can you check if the docker container is up, and gather some logs (`docker logs ekcp_ekcp-master_1` , be sure to replace ekcp_ekcp-master_1 with the container name) and which docker-compose file are you running?

**Comment by mudler** [comment]
As far as I can read from the docker docs [here](https://docs.docker.com/network/host/):

```
The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.
```

Most likely means you cannot run the API master node on a Mac, but it should be just fine for a worker, EKCP needs host network mode for API master as for now because it allocate ports to proxy the kube connections to the workers that are actually running the kind clusters, check the wiki for more examples: https://github.com/mudler/ekcp/wiki/Deployment-setups

**Comment by srlagisetty** [comment]
@mudler - Thanks a lot. I will check and get back if needed

**Comment by mudler** [comment]
#9  opened as a follow-up, closing this now :+1:
